name: Stellar Expert Build and Release
on:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write
  contents: write
  attestations: write

jobs:
  release:
    uses: stellar-expert/soroban-build-workflow/.github/workflows/release.yml@8764eba5769e4ffb63883889c2db5cc12eb44ef8
    with:
      release_name: ${{ github.ref_name }}   # git tag as unique release name
      release_description: 'Contract release'   # text to attach to the release
      relative_path: '["contracts/hello-world"]'   # relative contract path
      package: 'hello-world'   # package name to build
      # make_target: 'build-dependencies'   # make target to invoke
    secrets:  # authentication tokens will be automatically created by GitHub
      release_token: ${{ secrets.GITHUB_TOKEN }}
